### ISSUE TITLE
factor_strategy.py 관련 질문

### ISSUE THREAD

**Issue by JongHyeonPart** [RAAILab/PyRA#6]
안녕하세요. 유익한 책을 출간해주신 덕분에 도움을 많이 받고 있습니다.

다름이 아니라 현재 멀티 팩터를 공부하면서 factor_strategy.py 코드를 보다가 질문이 있어서 글 남깁니다.

setups을 보면 파라미터에 'full_history'가 있는데, 실제 simulate_factor 함수의 input 파라미터를 보면 'full_history'라는 파라미터는 찾을 수가 없습니다.

혹시 이 부분에서 잘못된 파라미터가 들어간 것인지 확인을 부탁드려도 괜찮을까요? 실제로 터미널에서 실행하면 그 부분이 오류가 나오기는 합니다.

확인해주시면 감사드리겠습니다.
감사합니다.

**Comment by woongineer** [comment]
안녕하세요.

setups의 full_history는 없어진 파라미터입니다.
해당 부분 수정하였습니다.

자세히 말씀드리자면,
6.factor_strategy 파일에서는 월별 자산을 통해 전략을 구현하고, factor_strategy.py는 일별 자산을 출력하여서 7.multi factor strategy에서 사용합니다. 
해당 구분을 full_history 파라미터를 통해 구분하려 했으나, 코드를 간소화하기 위해 full_history를 지우다가 삭제하지 않은 부분이 남아있었던 것 같습니다.
기존에는 
```
    if not full_history:
        account.account_history = [item for item in account.account_history if
                                   item['date'].date() in month_end.date]
```
위와 같은 방법으로 월별/일별을 구분하였습니다.

오류를 찾아주셔서 감사하고 사과의 말씀을 드립니다.
감사합니다!
