### ISSUE TITLE
factor_strategy.py 코드 오류 수정 요청

### ISSUE THREAD

**Issue by JongHyeonPart** [RAAILab/PyRA#7]
안녕하세요. factor_strategy.py 코드에 오류가 있어서 다시 글 남기게 되었습니다.

calculate_momentum, calculate_lowvol 함수에서 데이터 재구조화 부분이 아래와 같이 되어 있습니다.

# 데이터 재구조화(OHLCV)
    data = ohlcv_data[['close', 'ticker']].reset_index().set_index(
        ['ticker', 'date']).unstack(level=0)
        
 이 부분에서 뒤에 ['close']를 넣지 않으면 MultiIndex가 되어 rebalance에서 오류가 나는 거 같습니다.

이 부분 수정 부탁드리겠습니다.

감사합니다.

**Comment by woongineer** [comment]
안녕하세요,

해당 부분 말씀주신 방식으로 수정하였습니다.

해당 부분은 jupyter에서만 고쳐졌고 factor_strategy.py에서는 누락되었습니다.
불편을 드려 죄송합니다.
감사합니다!
